import turtle
import time
s=turtle.getscreen()
turtle.title("Mattrab Logo !")
turtle.hideturtle()
t=turtle.Turtle()
t.clear()
t.penup()
t.goto(-150, 150)
t.pendown()
t.color("#5fcf80")
t.pen(fillcolor="#5fcf80", speed=1)
t.begin_fill()
t.forward(300)
t.right(90)
t.forward(300)
t.right(90)
t.forward(300)
t.right(90)
t.forward(300)
t.right(90)
t.end_fill()
t.color("white")
t.penup()
t.setpos(-110, -155)
t.pendown()
t.write('M', font=('ASAP Condensed', 200, 'bold'))
time.sleep(20)